### ISSUE TITLE
tilemap: external .tsx filesystem read breaks every wasm32-emscripten build since v1.31.0

### ISSUE THREAD

**Issue by apotema** [labelle-toolkit/labelle-gfx#355]
## Symptom

Any consumer that links the tilemap module and targets `wasm32-emscripten` fails to compile on Zig 0.16.0:

```
std/Io/Threaded.zig:15315:38: error: expected type 'os.linux.SIG__enum_1176', found 'u32'
        .{ .stopped = posix.W.STOPSIG(status) }
std/os/emscripten.zig:215:16: error: expected enum, found 'u32'
        return @enumFromInt(EXITSTATUS(s));
```

Both errors are inside Zig's std, not in gfx, and they are reached through `tilemap/src/tile_map.zig`:

```
readFileOwned            tilemap/src/tile_map.zig:1106   var threaded: std.Io.Threaded = .init(...)
resolveExternalTileset   tilemap/src/tile_map.zig
parseTileset → parseXml → loadFromMemoryWithOptions
labelle-engine tilemap_runtime.initInPlace → tilemap_mixin.addTilemap → save_load/load.zig loadGameState
```

Instantiating `std.Io.Threaded` pulls in its full vtable, including `childWait`, and that code does not compile for emscripten in 0.16.0. It only has to be *reachable* — no tilemap needs to exist at runtime.

## Since when

Introduced by 41bf37c (#336, resolve external `.tsx` tilesets), shipped in **v1.31.0**. v1.30.1 has no `Io.Threaded` in the tilemap and builds for wasm. Still present on `main` (c0208a4) and in v1.34.0.

## Impact

flying-platform-labelle's Fly.io web deploy has been red on every push to main since it repinned past 1.30.x — the failure was masked for four weeks by an unrelated CLI-version failure earlier in the same workflow (FP#847). Reproduced locally on FP main with gfx 1.32.0, Zig 0.16.0, emsdk 4.0.9: fails as above; with the guard below, the build completes and emits `game.wasm`.

## Fix

The read is meaningless on wasm anyway — there is no filesystem to resolve `base_path/source` against, and `read_external_from_filesystem` already documents `error.ExternalTilesetUnsupported` as the answer when no directory is available. A comptime guard in `readFileOwned` on `.emscripten`/`.wasi`/`.freestanding` returning that error keeps `Io.Threaded` out of the wasm analysis entirely. Verified end to end against the FP wasm build. PR follows.

Worth a `-target wasm32-emscripten -fno-emit-bin` cross-check in `tests.yml` so this cannot regress silently; the repo has no wasm compile coverage today.

**Comment by apotema** [comment]
Reproduced again on Flying Platform PR #879 with released gfx 1.32.0, engine 2.20.0, Zig 0.16.0 and emsdk 4.0.9, running on Blacksmith Ubuntu 24.04.

Full reference trace: https://github.com/moca-tecnologia/flying-platform-labelle/actions/runs/34784804412

The chain is:
save_load_smoke_controller.tick -> save_load.performLoadFile -> engine.loadGameState -> tilemap_mixin.addTilemap -> tilemap_runtime.initInPlace -> loadFromMemoryWithOptions -> parseXml -> resolveExternalTileset -> readFileOwned -> std.Io.Threaded.io -> childWait.

The two errors match this issue: Threaded.zig:15315 expects a signal enum but gets u32; emscripten.zig:215 applies enumFromInt where u32 is expected. The newly added smoke controller makes this path reachable even when no tilemap is loaded at runtime.

FP #879 now rejects direct disk-save loading at comptime on Emscripten, before entering the engine reset/load path; the game already uses std.Io.failing for browser disk persistence. The subsequent run 34784977615 still fails with the same std errors, so the consumer guard is insufficient. The current #356 head (636d93e) passes a fresh local zig build wasm-check, and its existing CI is green. A released gfx version containing #356 remains needed.
